# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Path', models.TextField()),
                ('Extension', models.TextField()),
                ('Size', models.TextField()),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
